In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('housingData.csv')

In [3]:
print(df.head())

   RegionName           City State          Metro     CountyName  SizeRank  \
0       10023       New York    NY       New York       New York         1
1       60614        Chicago    IL        Chicago           Cook         2
2       10002       New York    NY       New York       New York         3
3       94109  San Francisco    CA  San Francisco  San Francisco         4
4       11375       New York    NY       New York         Queens         5

   2010-01  2010-02  2010-03  2010-04     ...           2016-12      2017-01  \
0      NaN      NaN      NaN      NaN     ...       1942.457079  1944.164364
1      NaN      NaN      NaN      NaN     ...        389.933333   398.787141
2      NaN      NaN      NaN      NaN     ...       2010.594079  2013.888889
3      NaN      NaN      NaN      NaN     ...       1114.761669  1130.438822
4      NaN      NaN      NaN      NaN     ...        407.142857   407.435065

       2017-02      2017-03      2017-04      2017-05      2017-06  \
0  1944.818304  1970.909091  1948.772788  1948.772788  1963.986600
1   389.933333   387.716667   400.250000   395.014111   403.930131
2  2162.634653  2162.634653  2069.301911  2030.548068  2059.174217
3  1128.301887  1107.985355  1099.541675  1212.335693  1162.500000
4   408.257713   413.571429   427.630909   453.636364   453.901515

       2017-07      2017-08      2017-09
0  1964.496665  1984.060403  1964.496665
1   413.254630   384.780739   379.890370
2  2069.301911  2062.192438  2049.121663
3  1157.827405  1104.972376  1104.972376
4   447.370130   449.285714   437.326892

[5 rows x 99 columns]

In [8]:
df.dropna(inplace=True)

In [9]:
df.drop_duplicates()

,RegionName,City,State,Metro,CountyName,SizeRank,2010-01,2010-02,2010-03,2010-04,...,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09
8,37211,Nashville,TN,Nashville,Davidson,9,106.102388,105.430923,103.379310,102.990109,...,146.949891,155.577668,152.777778,151.531450,146.382611,153.889789,154.148631,155.024395,160.279605,168.315789
9,37013,Nashville,TN,Nashville,Davidson,10,83.384853,85.882353,83.624655,83.368092,...,112.898403,115.465745,115.131579,113.567073,116.037736,116.037736,118.343195,115.384615,116.935484,116.158403
10,60618,Chicago,IL,Chicago,Cook,11,236.500000,237.759715,237.692308,234.312500,...,396.171927,357.142857,360.862755,370.689474,357.049320,343.086735,369.889224,370.192308,401.444788,351.730519
15,90046,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,16,565.123789,550.314465,544.029851,518.230258,...,776.824619,789.682540,736.885246,708.954478,775.862069,790.918691,786.434682,805.849409,822.667068,806.374881
17,20009,Washington,DC,Washington,District of Columbia,18,501.404213,507.433719,527.944112,504.536636,...,621.014787,617.664093,639.059305,636.587436,662.678451,653.390681,643.241711,639.858809,657.000000,662.025316
19,63376,Saint Peters,MO,St. Louis,Saint Charles,20,111.988304,110.801636,111.988304,110.801157,...,108.709386,100.343051,102.586879,109.296875,109.546166,111.166008,120.981570,121.502643,115.384615,114.770790
21,60629,Chicago,IL,Chicago,Cook,22,148.148148,147.267433,147.980324,149.373192,...,152.685185,154.218107,168.822394,176.702863,172.234098,171.632857,168.970406,167.885375,161.722488,160.521062
23,23464,Virginia Beach,VA,Virginia Beach,Virginia Beach City,24,136.506623,136.326499,136.506623,137.240869,...,107.570372,115.274725,113.144147,118.051479,118.635363,126.677238,120.401463,118.750000,117.557989,116.826504
24,7030,Hoboken,NJ,New York,Hudson,25,469.426702,471.026301,476.976542,468.724367,...,691.270235,701.278444,700.689383,698.689956,699.340764,700.906205,706.990756,694.715835,699.222716,700.561010
25,28277,Charlotte,NC,Charlotte,Mecklenburg,26,108.186620,106.867626,106.822811,105.620210,...,127.209625,126.746324,127.096774,125.809353,126.811594,127.291242,128.630515,133.410223,135.636769,133.162103
28,33160,Sunny Isles Beach,FL,Miami-Fort Lauderdale,Miami-Dade,29,241.144201,241.144201,242.586491,239.919355,...,397.333988,390.021547,402.140673,400.390625,397.661606,394.802599,399.022935,397.602853,381.482546,380.611216
29,33139,Miami Beach,FL,Miami-Fort Lauderdale,Miami-Dade,30,476.851852,468.930636,451.277955,452.000000,...,652.528548,666.974000,672.926448,652.173913,658.735238,650.422604,665.883049,680.147059,652.475248,681.761787
36,23462,Virginia Beach,VA,Virginia Beach,Virginia Beach City,37,135.374801,135.103926,133.591980,135.261194,...,116.525424,116.716189,121.856743,122.568093,127.790938,125.839329,125.809062,125.000000,124.122465,122.453427
41,87111,Albuquerque,NM,Albuquerque,Bernalillo,42,138.321799,134.523857,132.539817,134.551495,...,131.417228,121.571072,135.009561,129.498270,131.399545,136.946387,136.946387,138.801891,133.858568,133.181358
44,98052,Redmond,WA,Seattle,King,45,254.569716,246.235607,248.565714,242.494226,...,305.432736,315.222335,337.569500,338.950144,363.440406,363.636364,363.636364,374.629196,374.681010,368.814192
45,6010,Bristol,CT,Hartford,Hartford,46,134.805361,134.364821,134.045077,130.784314,...,110.034130,110.380951,106.975527,105.128205,104.579371,108.024691,113.168724,114.292498,110.576923,111.015326
49,2169,Quincy,MA,Boston,Norfolk,50,246.735395,247.217929,246.630281,247.558815,...,291.510025,314.193754,312.044547,344.589874,341.985413,351.696446,354.598193,359.626582,353.493222,330.753661
50,33009,Hallandale,FL,Miami-Fort Lauderdale,Broward,51,165.269608,164.918159,160.634921,153.571429,...,236.819034,231.855670,230.128205,230.128205,229.681979,226.699670,227.212704,228.355144,232.978723,234.394137
54,44060,Mentor,OH,Cleveland,Lake,55,87.566306,90.980044,91.059028,90.322581,...,76.908867,73.830049,73.581691,77.074156,75.729435,83.086700,86.254061,84.726829,86.209677,85.327784
56,65807,Springfield,MO,Springfield,Greene,57,89.366516,89.896024,90.317887,88.661345,...,77.604657,79.349291,79.698582,73.877416,74.056916,76.777804,82.693026,78.273810,78.273810,86.994949
58,60634,Chicago,IL,Chicago,Cook,59,206.334520,202.826087,205.578512,205.578512,...,223.290598,238.589212,229.645454,240.547321,264.500000,265.964912,277.229396,274.251497,274.058178,264.740211
60,6902,Stamford,CT,Stamford,Fairfield,61,292.500000,292.255155,292.255155,295.505618,...,255.102041,248.824451,251.998433,257.086280,267.857143,267.071429,267.857143,267.857143,268.310912,266.687192
63,92109,San Diego,CA,San Diego,San Diego,64,587.254902,566.654963,580.085784,593.782730,...,590.062112,606.305578,633.830479,601.806404,589.205742,636.271839,667.780749,652.101124,652.505447,747.058824
65,44256,Medina,OH,Cleveland,Medina,66,98.080134,107.087939,102.582306,105.766423,...,97.907742,101.562500,100.531785,101.571165,100.332203,105.700252,105.012818,104.123056,101.960784,102.982955
66,33908,Fort Myers,FL,Fort Myers,Lee,67,138.552020,137.344033,135.254931,135.885818,...,149.016100,150.178784,148.767240,151.274063,150.846647,150.624267,148.376408,149.289100,149.372811,150.140845
69,89117,Las Vegas,NV,Las Vegas,Clark,70,67.134269,67.134269,65.030060,64.971170,...,119.294606,120.139441,119.633020,119.796954,126.252505,128.108515,129.441624,133.408072,140.180361,139.328099
71,43130,Lancaster,OH,Columbus,Fairfield,72,84.053501,82.052980,81.686914,83.735758,...,81.944444,80.620660,73.606272,78.835775,82.178932,85.363248,91.198845,93.951613,87.803487,96.079882
80,87120,Albuquerque,NM,Albuquerque,Bernalillo,81,116.982742,114.671517,115.325191,114.671517,...,121.915400,125.625466,122.213047,119.047619,117.930333,122.175141,121.898502,125.141998,124.425287,122.504537
82,46307,Crown Point,IN,Chicago,Lake,83,114.807725,114.529285,115.869565,114.670997,...,119.501163,120.446429,122.693939,122.954957,120.066540,115.619835,118.918919,113.598326,114.164087,116.744548
84,80134,Parker,CO,Denver,Douglas,85,152.656819,155.452959,155.452959,155.462185,...,224.812656,223.428584,222.411664,224.741734,227.606446,222.508591,224.278144,222.219638,231.117534,231.117534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1400,34432,Dunnellon,FL,Homosassa Springs,Citrus,1401,96.752449,94.821298,90.917914,89.495508,...,83.642142,79.959920,81.007194,80.626723,86.064426,86.104513,94.319776,92.821370,96.631012,97.805457
1406,28465,Oak Island,NC,Myrtle Beach,Brunswick,1407,190.345059,203.736370,206.678700,206.170547,...,185.302198,173.767038,172.453704,186.965812,184.438228,187.395833,189.095366,187.179487,188.787966,192.604167
1408,29920,Saint Helena Island,SC,Hilton Head Island,Beaufort,1409,309.343315,309.343315,304.268293,299.166667,...,205.657492,199.510151,203.703704,201.417069,208.149780,210.355987,210.106383,211.702128,218.324720,220.370370
1410,4090,Wells,ME,Portland,York,1411,187.320838,182.674437,179.674689,190.392041,...,278.867287,285.138889,296.864686,283.944444,270.677861,271.666667,286.301370,286.715041,284.722222,284.512274
1411,97367,Lincoln City,OR,Newport,Lincoln,1412,232.799145,232.978723,235.518024,223.518851,...,205.347122,215.833333,207.598784,214.630872,216.378066,215.504469,222.965820,221.478328,219.606618,220.588235
1412,28467,Carolina Shores,NC,Myrtle Beach,Brunswick,1413,132.674023,128.890800,133.139051,130.549897,...,86.285195,87.719298,89.826840,90.683606,96.898872,98.235134,105.470969,100.728960,98.802073,98.374284
1413,99114,Colville,WA,Spokane,Stevens,1414,130.525192,129.889669,132.082452,138.070506,...,130.208333,128.255208,138.310185,138.640429,133.282697,138.815789,138.640429,138.310185,129.385965,138.640429
1414,2673,Yarmouth,MA,Cape Cod,Barnstable,1415,241.029412,235.782135,230.673077,217.117988,...,262.229971,269.925474,253.135775,234.449761,266.087963,249.074074,248.015873,264.932563,259.120370,272.174658
1417,33955,Punta Gorda,FL,Punta Gorda,Charlotte,1418,149.004924,144.757427,138.564274,138.564274,...,163.915858,168.206357,156.614786,162.373222,167.516472,167.649123,167.649123,159.122203,161.528315,165.791775
1419,2631,Brewster,MA,Cape Cod,Barnstable,1420,235.089370,218.881857,214.662447,214.662447,...,244.590781,249.294450,265.017668,258.823529,258.823529,257.142857,242.034450,244.919786,239.572193,238.099538
1421,34452,Inverness,FL,Homosassa Springs,Citrus,1422,74.140836,73.441763,68.782210,67.536232,...,75.758870,74.253410,72.010870,71.900096,78.351449,80.885529,80.258841,78.125000,83.750371,88.118812
1426,29401,Charleston,SC,Charleston,Charleston,1427,466.065879,464.814815,467.763277,466.065879,...,550.957854,542.778003,544.664032,537.094281,565.201205,556.304249,536.171662,528.402521,532.457496,532.457496
1427,92314,Big Bear City,CA,Riverside,San Bernardino,1428,169.944853,168.269231,160.714286,158.333333,...,191.441513,191.012397,191.012397,191.830065,200.300750,204.454719,210.394737,205.084909,206.366995,209.237229
1432,34453,Inverness,FL,Homosassa Springs,Citrus,1433,71.949948,71.193866,71.061524,69.839394,...,71.987642,75.035535,79.925829,79.663963,84.047308,85.790813,76.323988,72.631579,73.578947,68.507043
1435,34217,Holmes Beach,FL,North Port-Sarasota-Bradenton,Manatee,1436,341.902314,341.660112,346.956522,332.217322,...,427.246790,417.942971,411.037891,393.407186,399.231951,433.188908,405.032468,389.035928,415.951973,434.222049
1438,63144,Brentwood,MO,St. Louis,Saint Louis,1439,163.730596,166.679407,166.555556,167.112805,...,167.755133,167.380816,161.616162,163.124616,169.425596,174.376869,170.031881,168.451025,173.495370,174.158654
1445,34429,Crystal River,FL,Homosassa Springs,Citrus,1446,96.229698,96.050870,93.451143,91.570216,...,95.440542,94.942493,94.362745,93.680556,94.074576,106.973290,103.583539,110.028054,110.416667,107.076350
1446,28428,Carolina Beach,NC,Wilmington,New Hanover,1447,260.066980,263.544686,260.066980,265.008819,...,250.185863,249.128357,247.485760,256.827136,261.989796,264.423077,261.989796,263.265306,263.844192,267.857143
1450,80487,Steamboat Springs,CO,Steamboat Springs,Routt,1451,329.950576,327.160494,328.467153,331.238653,...,340.650407,342.829077,335.786569,334.356967,328.750747,333.697047,335.721225,338.899804,341.269165,341.269165
1466,32456,Port Saint Joe,FL,Panama City,Gulf,1467,247.423679,228.423629,228.693994,244.357213,...,200.980392,194.490760,195.775998,225.000000,222.727273,220.088384,220.088384,229.289941,240.337645,220.559742
1472,92315,Big Bear Lake,CA,Riverside,San Bernardino,1473,226.320755,225.135624,218.996711,223.359002,...,236.894115,245.014245,240.497076,241.133312,248.772598,249.358974,262.304251,267.272046,267.272046,260.274753
1474,2657,Provincetown,MA,Cape Cod,Barnstable,1475,529.919803,527.749122,525.256470,525.256470,...,646.312317,652.884615,643.042913,652.307088,630.353929,643.042913,638.931223,671.382531,675.813008,692.094313
1488,33956,Saint James City,FL,Fort Myers,Lee,1489,198.784722,191.507024,189.839506,180.981047,...,201.045857,195.536562,195.536562,192.708333,195.536562,198.229462,207.427536,199.667616,205.336142,207.208392
1489,33043,Big Pine Key,FL,Key West,Monroe,1490,338.135593,336.516854,328.138780,337.326224,...,389.939693,391.494002,391.494002,407.191898,418.750000,418.781981,432.186235,433.007476,435.199653,432.291667
1495,28605,Blowing Rock,NC,Boone,Watauga,1496,255.769613,250.885316,253.214286,242.502157,...,208.649469,208.649469,209.083257,206.920415,207.200000,219.447968,237.278675,229.670862,215.200000,216.264773
1505,28512,Atlantic Beach,NC,Morehead City,Carteret,1506,281.371179,292.560976,280.637255,278.692560,...,240.384615,239.983974,238.154762,238.154762,239.603570,238.822526,238.822526,238.609113,238.862196,239.932886
1509,97394,Waldport,OR,Newport,Lincoln,1510,203.705693,209.421112,202.255639,204.166667,...,187.411301,193.571950,187.411301,189.046211,188.224498,185.362650,187.500000,189.554419,185.818450,180.722892
1520,28746,Lake Lure,NC,Forest City,Rutherford,1521,190.000000,192.902615,190.000000,194.743935,...,146.212121,149.732773,156.434783,155.097922,162.500000,161.675532,162.500000,155.880420,153.125000,146.566869
1523,85933,Overgaard,AZ,Show Low,Navajo,1524,136.317136,135.866901,135.254917,131.719551,...,125.847882,129.353904,111.517857,120.375410,122.950820,122.766896,122.766896,127.405991,127.405991,127.405991
1530,78597,South Padre Island,TX,Brownsville,Cameron,1531,218.940248,219.435028,225.000000,219.795792,...,200.493523,199.440448,189.043035,201.660735,204.708184,201.660735,206.882528,202.973169,200.493523,203.409091

In [10]:
print(df.head())

    RegionName         City State                           Metro  \
8        37211    Nashville    TN                       Nashville
9        37013    Nashville    TN                       Nashville
10       60618      Chicago    IL                         Chicago
15       90046  Los Angeles    CA  Los Angeles-Long Beach-Anaheim
17       20009   Washington    DC                      Washington

              CountyName  SizeRank     2010-01     2010-02     2010-03  \
8               Davidson         9  106.102388  105.430923  103.379310
9               Davidson        10   83.384853   85.882353   83.624655
10                  Cook        11  236.500000  237.759715  237.692308
15           Los Angeles        16  565.123789  550.314465  544.029851
17  District of Columbia        18  501.404213  507.433719  527.944112

       2010-04     ...         2016-12     2017-01     2017-02     2017-03  \
8   102.990109     ...      146.949891  155.577668  152.777778  151.531450
9    83.368092     ...      112.898403  115.465745  115.131579  113.567073
10  234.312500     ...      396.171927  357.142857  360.862755  370.689474
15  518.230258     ...      776.824619  789.682540  736.885246  708.954478
17  504.536636     ...      621.014787  617.664093  639.059305  636.587436

       2017-04     2017-05     2017-06     2017-07     2017-08     2017-09
8   146.382611  153.889789  154.148631  155.024395  160.279605  168.315789
9   116.037736  116.037736  118.343195  115.384615  116.935484  116.158403
10  357.049320  343.086735  369.889224  370.192308  401.444788  351.730519
15  775.862069  790.918691  786.434682  805.849409  822.667068  806.374881
17  662.678451  653.390681  643.241711  639.858809  657.000000  662.025316

[5 rows x 99 columns]

In [11]:
df.tail()

,RegionName,City,State,Metro,CountyName,SizeRank,2010-01,2010-02,2010-03,2010-04,...,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09
1505,28512,Atlantic Beach,NC,Morehead City,Carteret,1506,281.371179,292.560976,280.637255,278.692560,...,240.384615,239.983974,238.154762,238.154762,239.603570,238.822526,238.822526,238.609113,238.862196,239.932886
1509,97394,Waldport,OR,Newport,Lincoln,1510,203.705693,209.421112,202.255639,204.166667,...,187.411301,193.571950,187.411301,189.046211,188.224498,185.362650,187.500000,189.554419,185.818450,180.722892
1520,28746,Lake Lure,NC,Forest City,Rutherford,1521,190.000000,192.902615,190.000000,194.743935,...,146.212121,149.732773,156.434783,155.097922,162.500000,161.675532,162.500000,155.880420,153.125000,146.566869
1523,85933,Overgaard,AZ,Show Low,Navajo,1524,136.317136,135.866901,135.254917,131.719551,...,125.847882,129.353904,111.517857,120.375410,122.950820,122.766896,122.766896,127.405991,127.405991,127.405991
1530,78597,South Padre Island,TX,Brownsville,Cameron,1531,218.940248,219.435028,225.000000,219.795792,...,200.493523,199.440448,189.043035,201.660735,204.708184,201.660735,206.882528,202.973169,200.493523,203.409091

In [12]:
df.set_index('City', inplace=True)

In [13]:
df.to_csv('newHsngData.csv')

In [14]:
pd.read_csv('newHsngData.csv')

,City,RegionName,State,Metro,CountyName,SizeRank,2010-01,2010-02,2010-03,2010-04,...,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09
0,Nashville,37211,TN,Nashville,Davidson,9,106.102388,105.430923,103.379310,102.990109,...,146.949891,155.577668,152.777778,151.531450,146.382611,153.889789,154.148631,155.024395,160.279605,168.315789
1,Nashville,37013,TN,Nashville,Davidson,10,83.384853,85.882353,83.624655,83.368092,...,112.898403,115.465745,115.131579,113.567073,116.037736,116.037736,118.343195,115.384615,116.935484,116.158403
2,Chicago,60618,IL,Chicago,Cook,11,236.500000,237.759715,237.692308,234.312500,...,396.171927,357.142857,360.862755,370.689474,357.049320,343.086735,369.889224,370.192308,401.444788,351.730519
3,Los Angeles,90046,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,16,565.123789,550.314465,544.029851,518.230258,...,776.824619,789.682540,736.885246,708.954478,775.862069,790.918691,786.434682,805.849409,822.667068,806.374881
4,Washington,20009,DC,Washington,District of Columbia,18,501.404213,507.433719,527.944112,504.536636,...,621.014787,617.664093,639.059305,636.587436,662.678451,653.390681,643.241711,639.858809,657.000000,662.025316
5,Saint Peters,63376,MO,St. Louis,Saint Charles,20,111.988304,110.801636,111.988304,110.801157,...,108.709386,100.343051,102.586879,109.296875,109.546166,111.166008,120.981570,121.502643,115.384615,114.770790
6,Chicago,60629,IL,Chicago,Cook,22,148.148148,147.267433,147.980324,149.373192,...,152.685185,154.218107,168.822394,176.702863,172.234098,171.632857,168.970406,167.885375,161.722488,160.521062
7,Virginia Beach,23464,VA,Virginia Beach,Virginia Beach City,24,136.506623,136.326499,136.506623,137.240869,...,107.570372,115.274725,113.144147,118.051479,118.635363,126.677238,120.401463,118.750000,117.557989,116.826504
8,Hoboken,7030,NJ,New York,Hudson,25,469.426702,471.026301,476.976542,468.724367,...,691.270235,701.278444,700.689383,698.689956,699.340764,700.906205,706.990756,694.715835,699.222716,700.561010
9,Charlotte,28277,NC,Charlotte,Mecklenburg,26,108.186620,106.867626,106.822811,105.620210,...,127.209625,126.746324,127.096774,125.809353,126.811594,127.291242,128.630515,133.410223,135.636769,133.162103
10,Sunny Isles Beach,33160,FL,Miami-Fort Lauderdale,Miami-Dade,29,241.144201,241.144201,242.586491,239.919355,...,397.333988,390.021547,402.140673,400.390625,397.661606,394.802599,399.022935,397.602853,381.482546,380.611216
11,Miami Beach,33139,FL,Miami-Fort Lauderdale,Miami-Dade,30,476.851852,468.930636,451.277955,452.000000,...,652.528548,666.974000,672.926448,652.173913,658.735238,650.422604,665.883049,680.147059,652.475248,681.761787
12,Virginia Beach,23462,VA,Virginia Beach,Virginia Beach City,37,135.374801,135.103926,133.591980,135.261194,...,116.525424,116.716189,121.856743,122.568093,127.790938,125.839329,125.809062,125.000000,124.122465,122.453427
13,Albuquerque,87111,NM,Albuquerque,Bernalillo,42,138.321799,134.523857,132.539817,134.551495,...,131.417228,121.571072,135.009561,129.498270,131.399545,136.946387,136.946387,138.801891,133.858568,133.181358
14,Redmond,98052,WA,Seattle,King,45,254.569716,246.235607,248.565714,242.494226,...,305.432736,315.222335,337.569500,338.950144,363.440406,363.636364,363.636364,374.629196,374.681010,368.814192
15,Bristol,6010,CT,Hartford,Hartford,46,134.805361,134.364821,134.045077,130.784314,...,110.034130,110.380951,106.975527,105.128205,104.579371,108.024691,113.168724,114.292498,110.576923,111.015326
16,Quincy,2169,MA,Boston,Norfolk,50,246.735395,247.217929,246.630281,247.558815,...,291.510025,314.193754,312.044547,344.589874,341.985413,351.696446,354.598193,359.626582,353.493222,330.753661
17,Hallandale,33009,FL,Miami-Fort Lauderdale,Broward,51,165.269608,164.918159,160.634921,153.571429,...,236.819034,231.855670,230.128205,230.128205,229.681979,226.699670,227.212704,228.355144,232.978723,234.394137
18,Mentor,44060,OH,Cleveland,Lake,55,87.566306,90.980044,91.059028,90.322581,...,76.908867,73.830049,73.581691,77.074156,75.729435,83.086700,86.254061,84.726829,86.209677,85.327784
19,Springfield,65807,MO,Springfield,Greene,57,89.366516,89.896024,90.317887,88.661345,...,77.604657,79.349291,79.698582,73.877416,74.056916,76.777804,82.693026,78.273810,78.273810,86.994949
20,Chicago,60634,IL,Chicago,Cook,59,206.334520,202.826087,205.578512,205.578512,...,223.290598,238.589212,229.645454,240.547321,264.500000,265.964912,277.229396,274.251497,274.058178,264.740211
21,Stamford,6902,CT,Stamford,Fairfield,61,292.500000,292.255155,292.255155,295.505618,...,255.102041,248.824451,251.998433,257.086280,267.857143,267.071429,267.857143,267.857143,268.310912,266.687192
22,San Diego,92109,CA,San Diego,San Diego,64,587.254902,566.654963,580.085784,593.782730,...,590.062112,606.305578,633.830479,601.806404,589.205742,636.271839,667.780749,652.101124,652.505447,747.058824
23,Medina,44256,OH,Cleveland,Medina,66,98.080134,107.087939,102.582306,105.766423,...,97.907742,101.562500,100.531785,101.571165,100.332203,105.700252,105.012818,104.123056,101.960784,102.982955
24,Fort Myers,33908,FL,Fort Myers,Lee,67,138.552020,137.344033,135.254931,135.885818,...,149.016100,150.178784,148.767240,151.274063,150.846647,150.624267,148.376408,149.289100,149.372811,150.140845
25,Las Vegas,89117,NV,Las Vegas,Clark,70,67.134269,67.134269,65.030060,64.971170,...,119.294606,120.139441,119.633020,119.796954,126.252505,128.108515,129.441624,133.408072,140.180361,139.328099
26,Lancaster,43130,OH,Columbus,Fairfield,72,84.053501,82.052980,81.686914,83.735758,...,81.944444,80.620660,73.606272,78.835775,82.178932,85.363248,91.198845,93.951613,87.803487,96.079882
27,Albuquerque,87120,NM,Albuquerque,Bernalillo,81,116.982742,114.671517,115.325191,114.671517,...,121.915400,125.625466,122.213047,119.047619,117.930333,122.175141,121.898502,125.141998,124.425287,122.504537
28,Crown Point,46307,IN,Chicago,Lake,83,114.807725,114.529285,115.869565,114.670997,...,119.501163,120.446429,122.693939,122.954957,120.066540,115.619835,118.918919,113.598326,114.164087,116.744548
29,Parker,80134,CO,Denver,Douglas,85,152.656819,155.452959,155.452959,155.462185,...,224.812656,223.428584,222.411664,224.741734,227.606446,222.508591,224.278144,222.219638,231.117534,231.117534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,Dunnellon,34432,FL,Homosassa Springs,Citrus,1401,96.752449,94.821298,90.917914,89.495508,...,83.642142,79.959920,81.007194,80.626723,86.064426,86.104513,94.319776,92.821370,96.631012,97.805457
445,Oak Island,28465,NC,Myrtle Beach,Brunswick,1407,190.345059,203.736370,206.678700,206.170547,...,185.302198,173.767038,172.453704,186.965812,184.438228,187.395833,189.095366,187.179487,188.787966,192.604167
446,Saint Helena Island,29920,SC,Hilton Head Island,Beaufort,1409,309.343315,309.343315,304.268293,299.166667,...,205.657492,199.510151,203.703704,201.417069,208.149780,210.355987,210.106383,211.702128,218.324720,220.370370
447,Wells,4090,ME,Portland,York,1411,187.320838,182.674437,179.674689,190.392041,...,278.867287,285.138889,296.864686,283.944444,270.677861,271.666667,286.301370,286.715041,284.722222,284.512274
448,Lincoln City,97367,OR,Newport,Lincoln,1412,232.799145,232.978723,235.518024,223.518851,...,205.347122,215.833333,207.598784,214.630872,216.378066,215.504469,222.965820,221.478328,219.606618,220.588235
449,Carolina Shores,28467,NC,Myrtle Beach,Brunswick,1413,132.674023,128.890800,133.139051,130.549897,...,86.285195,87.719298,89.826840,90.683606,96.898872,98.235134,105.470969,100.728960,98.802073,98.374284
450,Colville,99114,WA,Spokane,Stevens,1414,130.525192,129.889669,132.082452,138.070506,...,130.208333,128.255208,138.310185,138.640429,133.282697,138.815789,138.640429,138.310185,129.385965,138.640429
451,Yarmouth,2673,MA,Cape Cod,Barnstable,1415,241.029412,235.782135,230.673077,217.117988,...,262.229971,269.925474,253.135775,234.449761,266.087963,249.074074,248.015873,264.932563,259.120370,272.174658
452,Punta Gorda,33955,FL,Punta Gorda,Charlotte,1418,149.004924,144.757427,138.564274,138.564274,...,163.915858,168.206357,156.614786,162.373222,167.516472,167.649123,167.649123,159.122203,161.528315,165.791775
453,Brewster,2631,MA,Cape Cod,Barnstable,1420,235.089370,218.881857,214.662447,214.662447,...,244.590781,249.294450,265.017668,258.823529,258.823529,257.142857,242.034450,244.919786,239.572193,238.099538
454,Inverness,34452,FL,Homosassa Springs,Citrus,1422,74.140836,73.441763,68.782210,67.536232,...,75.758870,74.253410,72.010870,71.900096,78.351449,80.885529,80.258841,78.125000,83.750371,88.118812
455,Charleston,29401,SC,Charleston,Charleston,1427,466.065879,464.814815,467.763277,466.065879,...,550.957854,542.778003,544.664032,537.094281,565.201205,556.304249,536.171662,528.402521,532.457496,532.457496
456,Big Bear City,92314,CA,Riverside,San Bernardino,1428,169.944853,168.269231,160.714286,158.333333,...,191.441513,191.012397,191.012397,191.830065,200.300750,204.454719,210.394737,205.084909,206.366995,209.237229
457,Inverness,34453,FL,Homosassa Springs,Citrus,1433,71.949948,71.193866,71.061524,69.839394,...,71.987642,75.035535,79.925829,79.663963,84.047308,85.790813,76.323988,72.631579,73.578947,68.507043
458,Holmes Beach,34217,FL,North Port-Sarasota-Bradenton,Manatee,1436,341.902314,341.660112,346.956522,332.217322,...,427.246790,417.942971,411.037891,393.407186,399.231951,433.188908,405.032468,389.035928,415.951973,434.222049
459,Brentwood,63144,MO,St. Louis,Saint Louis,1439,163.730596,166.679407,166.555556,167.112805,...,167.755133,167.380816,161.616162,163.124616,169.425596,174.376869,170.031881,168.451025,173.495370,174.158654
460,Crystal River,34429,FL,Homosassa Springs,Citrus,1446,96.229698,96.050870,93.451143,91.570216,...,95.440542,94.942493,94.362745,93.680556,94.074576,106.973290,103.583539,110.028054,110.416667,107.076350
461,Carolina Beach,28428,NC,Wilmington,New Hanover,1447,260.066980,263.544686,260.066980,265.008819,...,250.185863,249.128357,247.485760,256.827136,261.989796,264.423077,261.989796,263.265306,263.844192,267.857143
462,Steamboat Springs,80487,CO,Steamboat Springs,Routt,1451,329.950576,327.160494,328.467153,331.238653,...,340.650407,342.829077,335.786569,334.356967,328.750747,333.697047,335.721225,338.899804,341.269165,341.269165
463,Port Saint Joe,32456,FL,Panama City,Gulf,1467,247.423679,228.423629,228.693994,244.357213,...,200.980392,194.490760,195.775998,225.000000,222.727273,220.088384,220.088384,229.289941,240.337645,220.559742
464,Big Bear Lake,92315,CA,Riverside,San Bernardino,1473,226.320755,225.135624,218.996711,223.359002,...,236.894115,245.014245,240.497076,241.133312,248.772598,249.358974,262.304251,267.272046,267.272046,260.274753
465,Provincetown,2657,MA,Cape Cod,Barnstable,1475,529.919803,527.749122,525.256470,525.256470,...,646.312317,652.884615,643.042913,652.307088,630.353929,643.042913,638.931223,671.382531,675.813008,692.094313
466,Saint James City,33956,FL,Fort Myers,Lee,1489,198.784722,191.507024,189.839506,180.981047,...,201.045857,195.536562,195.536562,192.708333,195.536562,198.229462,207.427536,199.667616,205.336142,207.208392
467,Big Pine Key,33043,FL,Key West,Monroe,1490,338.135593,336.516854,328.138780,337.326224,...,389.939693,391.494002,391.494002,407.191898,418.750000,418.781981,432.186235,433.007476,435.199653,432.291667
468,Blowing Rock,28605,NC,Boone,Watauga,1496,255.769613,250.885316,253.214286,242.502157,...,208.649469,208.649469,209.083257,206.920415,207.200000,219.447968,237.278675,229.670862,215.200000,216.264773
469,Atlantic Beach,28512,NC,Morehead City,Carteret,1506,281.371179,292.560976,280.637255,278.692560,...,240.384615,239.983974,238.154762,238.154762,239.603570,238.822526,238.822526,238.609113,238.862196,239.932886
470,Waldport,97394,OR,Newport,Lincoln,1510,203.705693,209.421112,202.255639,204.166667,...,187.411301,193.571950,187.411301,189.046211,188.224498,185.362650,187.500000,189.554419,185.818450,180.722892
471,Lake Lure,28746,NC,Forest City,Rutherford,1521,190.000000,192.902615,190.000000,194.743935,...,146.212121,149.732773,156.434783,155.097922,162.500000,161.675532,162.500000,155.880420,153.125000,146.566869
472,Overgaard,85933,AZ,Show Low,Navajo,1524,136.317136,135.866901,135.254917,131.719551,...,125.847882,129.353904,111.517857,120.375410,122.950820,122.766896,122.766896,127.405991,127.405991,127.405991
473,South Padre Island,78597,TX,Brownsville,Cameron,1531,218.940248,219.435028,225.000000,219.795792,...,200.493523,199.440448,189.043035,201.660735,204.708184,201.660735,206.882528,202.973169,200.493523,203.409091

In [15]:
df.head()

,RegionName,State,Metro,CountyName,SizeRank,2010-01,2010-02,2010-03,2010-04,2010-05,...,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09
City,,,,,,,,,,,,,,,,,,,,,
Nashville,37211,TN,Nashville,Davidson,9,106.102388,105.430923,103.379310,102.990109,96.910279,...,146.949891,155.577668,152.777778,151.531450,146.382611,153.889789,154.148631,155.024395,160.279605,168.315789
Nashville,37013,TN,Nashville,Davidson,10,83.384853,85.882353,83.624655,83.368092,81.378367,...,112.898403,115.465745,115.131579,113.567073,116.037736,116.037736,118.343195,115.384615,116.935484,116.158403
Chicago,60618,IL,Chicago,Cook,11,236.500000,237.759715,237.692308,234.312500,232.575758,...,396.171927,357.142857,360.862755,370.689474,357.049320,343.086735,369.889224,370.192308,401.444788,351.730519
Los Angeles,90046,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,16,565.123789,550.314465,544.029851,518.230258,528.271701,...,776.824619,789.682540,736.885246,708.954478,775.862069,790.918691,786.434682,805.849409,822.667068,806.374881
Washington,20009,DC,Washington,District of Columbia,18,501.404213,507.433719,527.944112,504.536636,505.315663,...,621.014787,617.664093,639.059305,636.587436,662.678451,653.390681,643.241711,639.858809,657.000000,662.025316

In [16]:
df.to_html('newhtmlHousingData.html')

In [17]:
df_html = pd.read_html('newhtmlHousingData.html')

In [21]:
df_New = pd.read_csv('housingData.csv', names=['RegionName','City'])
df.head()

,RegionName,State,Metro,CountyName,SizeRank,2010-01,2010-02,2010-03,2010-04,2010-05,...,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09
City,,,,,,,,,,,,,,,,,,,,,
Nashville,37211,TN,Nashville,Davidson,9,106.102388,105.430923,103.379310,102.990109,96.910279,...,146.949891,155.577668,152.777778,151.531450,146.382611,153.889789,154.148631,155.024395,160.279605,168.315789
Nashville,37013,TN,Nashville,Davidson,10,83.384853,85.882353,83.624655,83.368092,81.378367,...,112.898403,115.465745,115.131579,113.567073,116.037736,116.037736,118.343195,115.384615,116.935484,116.158403
Chicago,60618,IL,Chicago,Cook,11,236.500000,237.759715,237.692308,234.312500,232.575758,...,396.171927,357.142857,360.862755,370.689474,357.049320,343.086735,369.889224,370.192308,401.444788,351.730519
Los Angeles,90046,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,16,565.123789,550.314465,544.029851,518.230258,528.271701,...,776.824619,789.682540,736.885246,708.954478,775.862069,790.918691,786.434682,805.849409,822.667068,806.374881
Washington,20009,DC,Washington,District of Columbia,18,501.404213,507.433719,527.944112,504.536636,505.315663,...,621.014787,617.664093,639.059305,636.587436,662.678451,653.390681,643.241711,639.858809,657.000000,662.025316

In [24]:
df.rename(columns={'City':'Town'},inplace=True)
df.head()

,RegionName,State,Metro,CountyName,SizeRank,2010-01,2010-02,2010-03,2010-04,2010-05,...,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09
City,,,,,,,,,,,,,,,,,,,,,
Nashville,37211,TN,Nashville,Davidson,9,106.102388,105.430923,103.379310,102.990109,96.910279,...,146.949891,155.577668,152.777778,151.531450,146.382611,153.889789,154.148631,155.024395,160.279605,168.315789
Nashville,37013,TN,Nashville,Davidson,10,83.384853,85.882353,83.624655,83.368092,81.378367,...,112.898403,115.465745,115.131579,113.567073,116.037736,116.037736,118.343195,115.384615,116.935484,116.158403
Chicago,60618,IL,Chicago,Cook,11,236.500000,237.759715,237.692308,234.312500,232.575758,...,396.171927,357.142857,360.862755,370.689474,357.049320,343.086735,369.889224,370.192308,401.444788,351.730519
Los Angeles,90046,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,16,565.123789,550.314465,544.029851,518.230258,528.271701,...,776.824619,789.682540,736.885246,708.954478,775.862069,790.918691,786.434682,805.849409,822.667068,806.374881
Washington,20009,DC,Washington,District of Columbia,18,501.404213,507.433719,527.944112,504.536636,505.315663,...,621.014787,617.664093,639.059305,636.587436,662.678451,653.390681,643.241711,639.858809,657.000000,662.025316

In [2]:
dfNew = pd.read_csv('ZILLOW-Z77006_ZRIFAH.csv')

In [3]:
dfNew.head()

         Date  Value
0  2018-08-31  1.392
1  2018-07-31  1.394
2  2018-06-30  1.396
3  2018-05-31  1.396
4  2018-04-30  1.396

In [4]:
dfNew.set_index('Date', inplace=True)

In [5]:
dfNew.to_html('ZillowHTML.html')

In [6]:
dfNew1 = pd.read_html('ZillowHTML.html')
dfNew1.head()

AttributeError: 'list' object has no attribute 'head'

In [8]:
dfNew.rename(columns= {'Value':'Values'})

            Values
Date
2018-08-31   1.392
2018-07-31   1.394
2018-06-30   1.396
2018-05-31   1.396
2018-04-30   1.396
2018-03-31   1.396
2018-02-28   1.394
2018-01-31   1.394
2017-12-31   1.394
2017-11-30   1.392
2017-10-31   1.388
2017-09-30   1.384
2017-08-31   1.380
2017-07-31   1.382
2017-06-30   1.382
2017-05-31   1.386
2017-04-30   1.390
2017-03-31   1.396
2017-02-28   1.404
2017-01-31   1.414
2016-12-31   1.430
2016-11-30   1.446
2016-10-31   1.460
2016-09-30   1.476
2016-08-31   1.490
2016-07-31   1.502
2016-06-30   1.502
2016-05-31   1.500
2016-04-30   1.488
2016-03-31   1.514
...            ...
2013-04-30   1.282
2013-03-31   1.272
2013-02-28   1.260
2013-01-31   1.248
2012-12-31   1.234
2012-11-30   1.224
2012-10-31   1.220
2012-09-30   1.216
2012-08-31   1.210
2012-07-31   1.204
2012-06-30   1.196
2012-05-31   1.188
2012-04-30   1.182
2012-03-31   1.178
2012-02-29   1.178
2012-01-31   1.182
2011-12-31   1.188
2011-11-30   1.200
2011-10-31   1.216
2011-09-30   1.226
2011-08-31   1.226
2011-07-31   1.220
2011-06-30   1.208
2011-05-31   1.198
2011-04-30   1.188
2011-03-31   1.184
2011-02-28   1.178
2011-01-31   1.176
2010-12-31   1.174
2010-11-30   1.176

[94 rows x 1 columns]